name: Deploy to Github Pages
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm install

      - name: Run deploy script
        run: |
          git config user.name "PavelescuVictor" && git config user.email "pavelescu.victor97@gmail.com"
          npm run gh-pages-deploy